spring:
  datasource:
    name: picc
    url: jdbc:mysql://127.0.0.1:3306/GOING_MERRY?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: new_password
    
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080
  
mybatis:
  type-aliases-package: package com.sdu.software.goingmerry.entity
  configuration: 
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/*.xml